# Generated by Django 4.1.3 on 2023-02-25 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tweet_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 2, 8, 58, 550977, tzinfo=datetime.timezone.utc)),
        ),
    ]
